AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Password:
    Type: String
    Description: New account password
  UserName:
    Type: String
    Description: Name of the User
  UsersGroup:
    Type: String
    Default: ReadOnlyGroup
    AllowedValues:
      - ReadOnlyGroup
      - FullAcessGroup

Conditions:
  Createpolicyfors3readonly: !Equals [!Ref UsersGroup, ReadOnlyGroup]
  Createpolicyfors3fullaccess: !Equals [!Ref UsersGroup, FullAcessGroup]

Resources:
  User:
    Type: 'AWS::IAM::User'
    Properties:
      LoginProfile:
        Password: !Ref Password
        Username: !Ref UserName
        
 
  UserGroup:
     Type: AWS::IAM::Group
  AdminGroup:
    Type: AWS::IAM::Group
 
  UsersProfile:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'UserGroup'
      Users: [!Ref 'User']
  AdminsGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AdminGroup'
      Users: [!Ref 'User']
      
  S3ReadOnlyPolicy:
    Type: 'AWS::IAM::Policy'
    Condition: Createpolicyfors3readonly
    Description: policy to have s3 read only access
    Properties:
      PolicyName: UsersPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 's3:get*'
              - 's3:list*'
            Resource: '*'
      Groups:
       - !Ref UserGroup

  S3FullAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Condition: Createpolicyfors3fullaccess
    Description: policy to have s3 full access
    Properties:
      PolicyName: UsersPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource: '*'
      Groups:
       - !Ref UserGroup
  UserKeys:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref User
Outputs:
  AccessKey:
    Value: !Ref UserKeys
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt 
      - UserKeys
      - SecretAccessKey
    Description: AWSSecretAccessKey of new user
